### PR TITLE
<dual()> bug fix; other bug notifications appended to <__init__.py>

### PR DESCRIPTION
**Pull request by FredLunnon**
Let me know if the notifications are too cryptic: 
I could always email you a test run.    WFL

### CODE REVIEW

**Comment by arsenovic** [comment]
this does not appear to contain any changes.

**Comment by FredLunnon** [comment]
URL is
    https://github.com/FredLunnon/clifford/blob/master/clifford/__init__.py
LInes 1812 onwards contain my additions, and detail 2 changes earlier.
I re-committed, but there were no changes.

  This is the first time I've tried branching & pull request, mind!
I'm a little suspicious of that URL --- is my change getting hidden from
you for some obscure reason?

WFL

**Comment by arsenovic** [comment]
if you are trying to submit a bug report then,  generally we use the 'issues'. if you want to fix something then you can do this with  a `pull request` . 

if you email me,  i might be able to help you.  alex@810lab.com

**Comment by arsenovic** [comment]
@FredLunnon , 
    i added your `dual` bugfix. the numpy array bug should have been fixed also. let me know if it works, and i can close this.

**Comment by FredLunnon** [comment]
@arsenovic

  Forked your current repo and reran the test: dual() and array bugs fixed OK;
print bug remains.

  Oddly, the URL generated for my current fork differs from the previous
(suspiciously long) one.  I wonder if there might be a connection with the
binary file problem fouling up my earlier pull request?  Incidentally, I blamed
XTools incorrectly for assigning duff MIME types: it turns out OSX is to blame,
specifically their UIT --- urinary tract infection, perhaps?

  This time I'll record all interactions; then perhaps we could raise the issue
with GitHub --- if it recurs.

  By the way, good move to re-assign  "*"  operator; noteworthy that R. Kern
even confused himself over it, when (presumably) he coded the  dual()  bug!

WFL

**Pull request closed without merging**
